name: cloudrun-deploy
on:
  pull_request:
    branches: master
  push:
    branches: master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  RUN_REGION: us-east1
  SA_KEY_JSON: ${{ secrets.GCP_CREDENTIALS }}
  
jobs:
  setup-build-publish-deploy:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - name: Setup GCP Credentials
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:  
        version: 'lastest'  
        #service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        project_id: ${{ secrets.GCP_PROJECT }}
        export_default_credentials: true
    
    # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        gcloud auth configure-docker
      
    # Build the Docker image
    - name: Build 
      run: |
        gcloud builds submit --tag gcr.io/$PROJECT_ID/$PROJECT_ID:$GITHUB_SHA
    
    # Push the Docker image   
    - name: Deploy  
      run: |
        gcloud run deploy $PROJECT_ID  --image gcr.io/$PROJECT_ID/$PROJECT_ID:$GITHUB_SHA \
        --platform managed \
        --allow-unauthenticated \
        --region $RUN_REGION
        
